
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMSUNG
 */
public class Pass extends javax.swing.JInternalFrame {
    Connection con;
    String sr="",s="";
    String dept ="";
    String ar ="";
    String an ="";
    String id = "";
    String cl = "";
    double c=0;
    double t =0;
    String ml = "";
    double tc;

    /**
     * Creates new form Pass
     */
    public Pass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dep = new javax.swing.JComboBox();
        arrival = new javax.swing.JComboBox();
        aname = new javax.swing.JComboBox();
        time = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        budgetf = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        aid = new javax.swing.JTextField();
        fare = new javax.swing.JTextField();
        fclass = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pno = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        tcost = new javax.swing.JTextField();
        f = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        meal = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        mealcost = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        depdate = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        asc = new javax.swing.JRadioButton();
        desc = new javax.swing.JRadioButton();
        sortcombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        searchcombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        setTitle("Passenger Details");
        setPreferredSize(new java.awt.Dimension(1146, 693));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Details"));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel1.setText("Port Of Departure");

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel2.setText("Port of Arrival");

        jLabel3.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel3.setText("Airlines Name");

        jLabel5.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel5.setText("Time of Departure");

        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });

        arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalActionPerformed(evt);
            }
        });

        aname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anameActionPerformed(evt);
            }
        });

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel11.setText("Class");

        jLabel13.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel13.setText("Fare");

        budgetf.setFont(new java.awt.Font("Castellar", 1, 10)); // NOI18N
        budgetf.setText("Budget Flight");
        budgetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetfActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel17.setText("Airlines ID");

        aid.setEditable(false);
        aid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aidActionPerformed(evt);
            }
        });

        fare.setEditable(false);
        fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareActionPerformed(evt);
            }
        });

        fclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First", "Business", "Economy" }));
        fclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fclassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(dep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aid)
                            .addComponent(fclass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fare)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(budgetf)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(arrival, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(time)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(budgetf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(34, 47, 343, 313);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Passenger Details"));
        jPanel2.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel6.setText("Passenger ID");

        jLabel7.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel7.setText("Passport Number");

        jLabel8.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel8.setText("Passenger Name");

        jLabel9.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel9.setText("<html><b>Total Cost</b></html>");

        jLabel10.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel10.setText("Sex");

        jLabel12.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel12.setText("Date ");

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });

        tcost.setEditable(false);
        tcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcostActionPerformed(evt);
            }
        });

        buttonGroup3.add(f);
        f.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        f.setText("Female");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        buttonGroup3.add(m);
        m.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        m.setSelected(true);
        m.setText("Male");

        jLabel14.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel14.setText("Meal");

        meal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Veg", "Non Veg" }));
        meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Add Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mealcost.setEditable(false);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setText("Cancel");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setText("Close");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        depdate.setCalendarPreferredSize(new java.awt.Dimension(337, 215));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(79, 79, 79)
                                .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pno, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(pname)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mealcost, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(depdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(f)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(m)
                        .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(depdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mealcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(m)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(f)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(65, 65, 65))))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(395, 47, 640, 313);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Passenger ID", "Passenger Name", "Passport Number", "Sex", "Airlines Name", "Airlines ID", "Departure ", "Arrival", "Date ", "Time", "Class", "Meal", "Total cost"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(18, 371, 1010, 98);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setText("Passenger Details");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(375, 0, 179, 25);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Search & Sort"));

        buttonGroup2.add(asc);
        asc.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        asc.setSelected(true);
        asc.setText("Ascending");
        asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascActionPerformed(evt);
            }
        });

        buttonGroup2.add(desc);
        desc.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        desc.setText("Descending");

        sortcombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        sortcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passenger ID", "Passenger Name", "Date", " " }));
        sortcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortcomboActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel15.setText("Search for");

        searchcombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        searchcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passenger ID", "Passenger Name", "Departure", "Arrival", " " }));
        searchcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcomboActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jLabel4.setText("Sort By");

        refresh.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(searchcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(sortcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(asc)
                        .addGap(18, 18, 18)
                        .addComponent(desc)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(sortcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(refresh)
                    .addComponent(asc)
                    .addComponent(desc))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(207, 480, 599, 100);
        getContentPane().add(dateChooserCombo1);
        dateChooserCombo1.setBounds(770, 20, 155, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            String ai = aid.getText();
            
            
            if(m.isSelected())
             s = "M";
            else if(f.isSelected())
             s = "F";
            String pi = pid.getText();
            String p = pno.getText();
            String pn = pname.getText();
            String dt = depdate.getText();
            String c = (String) fclass.getSelectedItem();
            String m = (String) meal.getSelectedItem();
             String ti = (String) time.getText();
            String tc = tcost.getText();
            
            String q = "Insert into ptbl values('"+pi+"','"+pn+"','"+p+"','"+s+"','"+ai+"','"+dt+"','"+c+"','"+m+"',"+tc+")";
            Statement st = con.createStatement();
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(this,"The record has been successfully added.");
            display();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        opencon();
        display(); 
        meal.setSelectedItem("Veg");
        
        Calendar cal=Calendar.getInstance();
        //System.out.println(cal);
        
        
        
        //depdate.setMinDate(cal);
        
        //depdate.getCalendar();
        //depdate.getJCalendar().setMinSelectableDate(new Date());
        
        //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 

        //depdate.setMinDate((cal.get(1)+"/"+(cal.get(2)+1)+"/"+cal.get(5)));        
        //Date date = new Date();
        //jDateChooser.setDate(date);
        
        
        
        try{
            String q = "select distinct dep from ftbl";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            String a="";
            while(rs.next()){
                a=rs.getString(1);
                dep.addItem(a);
            }
                
        cl  = (String) fclass.getSelectedItem();
        id=aid.getText(); 

        getFare(id, cl);
        
         
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            String j = JOptionPane.showInputDialog("Enter Passenger ID to be delted");
            String q = "Delete from ptbl where P_ID='"+j+"'";
            Statement st = con.createStatement();
            st.executeUpdate(q);
            display();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed
        // TODO add your handling code here:
        try{
            arrival.removeAllItems();
            dept = (String)dep.getSelectedItem();
             String q = "select  distinct arr from ftbl where dep = '"+dept+"'";
           
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            
            while(rs.next()){
                arrival.addItem(rs.getString(1));
            }
             getFare(id, cl);
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
    }//GEN-LAST:event_depActionPerformed

    private void anameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anameActionPerformed
        // TODO add your handling code here:
       
        try{
            dept = (String) dep.getSelectedItem();
            ar = (String) arrival.getSelectedItem();
            an = (String) aname.getSelectedItem();
            fclass.setSelectedItem("First");
            
            String q = "select  a_id,dep_time from ftbl where dep = '"+dept+"' and arr='"+ar+"' and a_name = '"+an+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            
            while(rs.next()){
                aid.setText(rs.getString(1));
                time.setText(rs.getString(2));
               }
            cl  = (String) fclass.getSelectedItem();
            id=aid.getText(); 
            getFare(id,cl);
      if(an.equalsIgnoreCase("air asia"))
           budgetf.setEnabled(true);
        else if(!an.equalsIgnoreCase("air asia"))
           budgetf.setEnabled(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_anameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String sr="";
            String s=(String)searchcombo.getSelectedItem();
            if(s.equalsIgnoreCase("passenger id"))
                sr=JOptionPane.showInputDialog("Passenger ID");
            else if(s.equalsIgnoreCase("flight name"))
                sr=JOptionPane.showInputDialog("Airlines");
            else if(s.equalsIgnoreCase("departure"))
                sr=JOptionPane.showInputDialog("Departure");
            else if(s.equalsIgnoreCase("arrival"))
                sr=JOptionPane.showInputDialog("Arrival");

            display();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ascActionPerformed

    private void sortcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortcomboActionPerformed
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_sortcomboActionPerformed

    private void searchcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchcomboActionPerformed

    private void arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalActionPerformed
        // TODO add your handling code here:
        try{
            aname.removeAllItems();
            dept=(String)dep.getSelectedItem();
            ar=(String)arrival.getSelectedItem();
            
            String q = "select distinct a_name from ftbl where dep = '"+dept+"' and arr='"+ar+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            while(rs.next()){
                aname.addItem(rs.getString(1));
             }
               
        }catch(Exception e){
            JOptionPane.showMessageDialog(this , e.getMessage());
                    
        }
      
    }//GEN-LAST:event_arrivalActionPerformed

    private void aidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_aidActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void fareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareActionPerformed

    private void fclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fclassActionPerformed
        cl  = (String) fclass.getSelectedItem();
        id=aid.getText(); 
        getFare(id,cl);

    }//GEN-LAST:event_fclassActionPerformed

    
    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
        try{
        String ai = aid.getText();
        String q = "select dep_time from ftbl where a_id='"+ai+"'";
            
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(q); 
            
        while(rs.next()){
            time.setText(rs.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
            
         
        
    }//GEN-LAST:event_timeActionPerformed

    private void mealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealActionPerformed
        // TODO add your handling code here:
        ml = (String)meal.getSelectedItem();
        if(ml.equalsIgnoreCase("non veg"))
            c = 700;
        else if(ml.equalsIgnoreCase("veg"))
            c = 400;
        //t = Double.parseDouble(fare.getText());   
        mealcost.setText(""+c);
        tcost.setText(t+c+"");
        
        
        
              
    }//GEN-LAST:event_mealActionPerformed

    private void tcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcostActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tcostActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        pid.setText("");
        pname.setText("");
        pno.setText("");
        //depdate.setText("");
        m.setSelected(true);
        meal.setSelectedItem("Veg");
        tcost.setText("");
        
       try{
           dep.removeAllItems();
           String q = "select distinct dep from ftbl";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            while(rs.next()){
                dep.addItem(rs.getString(1));
            }
       }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void budgetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetfActionPerformed
        // TODO add your handling code here:
        //if (aname.getSelectedItem("Air Asia")
          //      budgetf.setEnabled(false);
        
        //tc=Double.parseDouble(tcost.getText());
        //if(budgetf.isSelected()){
          //  tc=tc-(0.15*tc);
        //    tcost.setText(""+tc);
        
         
    }//GEN-LAST:event_budgetfActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed
void getFare(String id, String cls){
        try{
            String fr="";
            if(cls.equalsIgnoreCase("first"))
                fr="F_fare";
            else if(cls.equalsIgnoreCase("business"))
                fr="b_fare";
            else if(cls.equalsIgnoreCase("economy"))
                fr="e_fare";
            
            String q = "select "+fr+" from ftbl where a_id='"+id+"'";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            String a = "";
            while(rs.next()){
                a=rs.getString(1);
                fare.setText(a);
                t = Double.parseDouble(a);
            }
           
            tcost.setText(t+c+"");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    void opencon(){
        try{
        
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/fm","root",null);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

}
void display(){
    try{
        String q = "Select * from ftbl natural join ptbl";
        
        String s=(String)searchcombo.getSelectedItem();
        if(sr.length()>0){
            if(s.equalsIgnoreCase("Passenger id"))
                q+="where P_ID like '%"+sr+"%'";
            else if(s.equalsIgnoreCase("passenger name"))
                q+="where P_Name like '%"+sr+"%'";
            else if(s.equalsIgnoreCase("departure"))
                sr=JOptionPane.showInputDialog("Departure");
            else if(s.equalsIgnoreCase("arrival"))
                sr=JOptionPane.showInputDialog("Arrival");
        }
            String srt=(String) sortcombo.getSelectedItem();
            if(srt.equalsIgnoreCase("passenger id") && asc.isSelected())
                q+=" order by p_id";
            else if(srt.equalsIgnoreCase("passenger id") && desc.isSelected())
                q+=" order by p_id desc";
            if(srt.equalsIgnoreCase("passenger name") && asc.isSelected())
                q+=" order by p_name";
            else if(srt.equalsIgnoreCase("passenger name") && desc.isSelected())
                q+=" order by p_name desc";
            if(srt.equalsIgnoreCase("date") && asc.isSelected())
                q+=" order by date";
            else if(srt.equalsIgnoreCase("date") && desc.isSelected())
                q+=" order by date desc";
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(q);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        
        String d,a,an,ai,t,pi,p,pn,dt,c,f,m,tc;
        
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
        while(rs.next()){
            pi = rs.getString("p_id");
            pn = rs.getString("p_name");
            p = rs.getString("pass_no");
            s = rs.getString("sex");
            an = rs.getString("A_NAME");
            ai = rs.getString("A_ID");
            
            d = rs.getString("dep");
            a = rs.getString("arr");
            dt = rs.getString("date");
            t = rs.getString("dep_time");
            c = rs.getString("class");
            m = rs.getString("meal");
            tc = rs.getString("total_cost");
            Object nr[] = {pi,pn,p,s,an,ai,d,a,dt,t,c,m,tc};
            dtm.addRow(nr);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aid;
    private javax.swing.JComboBox aname;
    private javax.swing.JComboBox arrival;
    private javax.swing.JRadioButton asc;
    private javax.swing.JCheckBox budgetf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JComboBox dep;
    private datechooser.beans.DateChooserCombo depdate;
    private javax.swing.JRadioButton desc;
    private javax.swing.JRadioButton f;
    private javax.swing.JTextField fare;
    private javax.swing.JComboBox fclass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton m;
    private javax.swing.JComboBox meal;
    private javax.swing.JTextField mealcost;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pno;
    private javax.swing.JButton refresh;
    private javax.swing.JComboBox<String> searchcombo;
    private javax.swing.JComboBox<String> sortcombo;
    private javax.swing.JTextField tcost;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
