
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMSUNG
 */
public class Report extends javax.swing.JInternalFrame {
    Connection con;
    String an,dp,ar;
    

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aname = new javax.swing.JComboBox<>();
        arr = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporttbl = new javax.swing.JTable();
        from = new javax.swing.JComboBox<>();
        to = new javax.swing.JComboBox<>();
        dep = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("From");

        jLabel2.setText("To");

        label.setText("Airlines");

        jLabel3.setText("Departure");

        jLabel4.setText("Arrival");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel5.setText("Report");

        aname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anameActionPerformed(evt);
            }
        });

        arr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrActionPerformed(evt);
            }
        });

        reporttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Passenger ID", "Passenger Name", "Airlines", "Departure", "Arrival", "Date", "Total cost"
            }
        ));
        jScrollPane1.setViewportView(reporttbl);

        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });

        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });

        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(label)
                                        .addGap(40, 40, 40)
                                        .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(221, 221, 221)
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addComponent(arr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(arr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        opencon();
        try{
            
            from.removeAllItems();
            from.addItem("All");
            String q = "select  distinct date from ftbl natural join ptbl ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            
            while(rs.next()){
                from.addItem(rs.getString(1));
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
       
    }//GEN-LAST:event_formInternalFrameOpened

    private void anameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anameActionPerformed
        // TODO add your handling code here:
        
        try{
            dep.removeAllItems();
            dep.addItem("All");
            String an = (String) aname.getSelectedItem();
            String q = "select  distinct dep from ftbl natural join ptbl where a_name = '"+an+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            
            while(rs.next()){
                
                dep.addItem(rs.getString(1));
            }
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
            
        
    }//GEN-LAST:event_anameActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
        try{
                
            to.removeAllItems();
            to.addItem("All");
            String q = "select  distinct date from ftbl natural join ptbl ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            
            while(rs.next()){
                
                to.addItem(rs.getString(1));
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_fromActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
       try{
            aname.removeAllItems();
            aname.addItem("All");
            String q = "select  distinct a_name from ftbl ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            
            while(rs.next()){
                
                aname.addItem(rs.getString(1));
            }
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
   
    }//GEN-LAST:event_toActionPerformed

    private void arrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_arrActionPerformed

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed
        // TODO add your handling code here:
       try{
            arr.removeAllItems();
            arr.addItem("All");
            an = (String) aname.getSelectedItem();
            dp = (String) dep.getSelectedItem();
            
            String q = "select  distinct arr from ftbl where a_name = '"+an+"' and dep = '"+dp+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q); 
            
            while(rs.next()){
                
                arr.addItem(rs.getString(1));
            }
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
   
    }//GEN-LAST:event_depActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_jButton1ActionPerformed
void opencon(){
        try{
        
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/fm","root",null);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

}
    void display(){
    try{
        an = (String) aname.getSelectedItem();
        ar = (String) arr.getSelectedItem();
        dp = (String) dep.getSelectedItem();
        String fr = (String) from.getSelectedItem();
        String t = (String) to.getSelectedItem();
        
        // if fr or t is all then what will the query be 
        String q = "Select * from ptbl natural join ftbl ";
        String r = "";
        String s = " where ";
        String date = " date between '" +fr + "' and '"+t+"'";
        
        if(!an.equals("All"))
            r+=" a_name = '"+an+"'";
        
        if(!dp.equals("All")){
            if(r.length()>1)
                r+=" and";
            r+=" dep = '"+dp+"'";
        }
        if(!ar.equals("All")){
            if(r.length()>1)
                r+=" and";
            r+=" arr = '"+ar+"'";
        } 
        if(fr.equals("All") && !t.equals("All")){
            if(r.length()>1)
                r+=" and";
            r+=" date  <= '"+ t+"'"; 
        }
        
        if(t.equals("All") && !fr.equals("All")){
            if(r.length()>1)
                r+=" and";
            r+=" date  >= '"+ fr+"'"; 
        }
        
        if(!t.equals("All") && !fr.equals("All")){
            if(r.length()>1)
                r+=" and";
            r+=date; 
        }
        
        if(t.equals("All") && fr.equals("All")){
            if(r.length()>1)
                 q+= s + r;
        }        
        
        else if(r.length()>0)
          q+= s + r ;
        
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(q);
        DefaultTableModel dtm = (DefaultTableModel)reporttbl.getModel();
        
        String d,a,an1,pi,pn,dt,tc;
        
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
        
        while(rs.next()){
            pi = rs.getString("P_ID");
            pn = rs.getString("P_Name");
            an1 = rs.getString("A_NAME");
            d = rs.getString("Dep");
            a = rs.getString("Arr");
            dt = rs.getString("Date");
            tc = rs.getString("Total_Cost");
            Object nr[] = {pi,pn,an1,d,a,dt,tc};
            dtm.addRow(nr);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aname;
    private javax.swing.JComboBox<String> arr;
    private javax.swing.JComboBox dep;
    private javax.swing.JComboBox<String> from;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable reporttbl;
    private javax.swing.JComboBox<String> to;
    // End of variables declaration//GEN-END:variables
}
